### PR TITLE
New keyword is optional

### PR DESCRIPTION
**Pull request by Abhishek01039**

### CODE REVIEW

**Comment by Abhishek01039** [comment]
Hello @Hixie 
can you please review this PR?
Thanks

**Comment by Hixie** [comment]
This repo is sort of dead. Before we can accept patches to it, if we want to continue developing it under the Flutter label, we should move it to the `flutter/packages` repo. Might be easiest if you want to just take the package and run with it outside of the the Flutter org, though.

**Comment by Abhishek01039** [comment]
You mean to take this package and make a new package on top of it?
@Hixie

**Comment by Hixie** [comment]
Please feel free to do so.

**Comment by Abhishek01039** [comment]
Thanks @Hixie

**Comment by Abhishek01039** [comment]
hello @Hixie 
I have published the plugin https://pub.dev/packages/hf_retry
now you can deprecate this repo.
Thanks

**Comment by Hixie** [comment]
Can you file a bug on the main repo, cc'ing me, suggesting that? Thanks!

**Pull request closed without merging**
